application: outfitsforgoodpeople
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  
- url: /.*
  script: outfitsforgoodpeople.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

builtins:
- remote_api: on
